### ISSUE TITLE
Multiple issues with User-Photo-Gallery (user-photo-gallery) page  

### ISSUE THREAD

**Issue by coiby** [OpenSanghaFoundation/OSF#39]
**Describe the bug**
1. It shouldn't list the thumbnails (smaller images) of the profile photo
2. There are warnings on the page
![Screenshot_2024-05-24_20-52-50](https://github.com/OpenSanghaFoundation/OSF/assets/1511656/b018da0f-f395-4e05-97aa-b5da67a1c971)
3. A uploaded image doesn't show immediately on the page and refreshing the page is needed
4. "User this photo as profile photo" doesn't work.

**To Reproduce**
1. Go to [Profile](https://opensanghafoundation.org/newsite/profileit/)
2. Click on [User Photos](https://opensanghafoundation.org/newsite/profileit/user-photo-gallery/)

**Comment by coiby** [comment]
> 40x40 and 80x80 not shown
> foreach ($files as $file) {
> if ($file == "." || $file == "..") continue;
> if (strpos($file, '40x40') !== false || strpos($filename, '80x80') !== false) {
> continue; }

Profile Photo thumbnails could use different size. So the above fix fail to address the case where there are 120x120 thumbnails. Again, I strongly recommend to use UM [User Photos - Ultimate Member](https://ultimatemember.com/extensions/user-photos/) extension instead of rolling out own implementations.

**Comment by OSFOSF** [comment]
there are no 120x120 and um does not allow so no need to add the code forr 120x120

**Comment by coiby** [comment]
According to https://docs.ultimatemember.com/article/1542-profile-photo-size, obviously 190x190 exists and 120x120 can also exist if configured,

> The profile photo uploader creates several thumbnails (smaller images) and compresses images (only for JPEG images). 
> 
> Use setting "Profile Photo Thumbnail Sizes (px)" to set thumbnails sizes for profile photos. Default thumbnails sizes:
> 
> - 40px - small image (used for messages, etc.)
> - 80px - medium image (used for activity wall, groups, etc.)
> - 190px - main image (used for account, profile, members, etc.)
> 
> Screen _wp-admin > Ultimate Member > Settings > General > Uploads_
> 
> ![](https://lh4.googleusercontent.com/TIlLttZhgweR8mbCNfJBrQe-hYrEyNsTBxaoYhJK5AwseXMnNW7el6-kh3Y7rqjEsnabazfSggDypQxoZ1esiQAhEgdiE6AEoynH5T9IR2M0NgbpdEJavjdIKCSBhDay8gNo7WWc)
