### ISSUE TITLE
Messages and User Profile Don't Redirect Properly for those Without an Account

### ISSUE THREAD

**Issue by nowmichaelclark** [OpenSanghaFoundation/OSF#42]
**Describe the bug**
Those **without** an account are redirected to the OSF Home page when they click User Profile or Messages from the Profile Tab.

**To Reproduce**
1. Log Out or Use Incognito to go to [opensanghafoundation.org](opensanghafoundation.org)
2. Click on 'Profile' at the top. Then click on 'User Profile'.
3. See that this redirects to the Home Page.
4. Click on 'Profile' again at the top. Then click on 'Messages'.
5. See that this redirects to an empty messages page. 

**Expected behavior**
Clicking these buttons when not logged in can instead redirect to the Sign Up/Login page. Alternatively, there can be a redirect to a page that reads "Please login to see This Page".

**Screenshots**
https://github.com/OpenSanghaFoundation/OSF/assets/162073748/14a0ceaa-20ab-4b93-a498-8d786929d50a

**Comment by coiby** [comment]
Hi @OSFOSF,

How did you manage to redirect the register page  to to register-2 page? Maybe we fix this issue in the same way.

**Comment by OSFOSF** [comment]
that was done automatically when the page was added and could be fixed on the login page
    On Saturday, June 1, 2024 at 05:39:48 PM GMT+7, Coiby ***@***.***> wrote:  
 
 


Hi @OSFOSF,

How did you manage to redirect the register page to to register-2 page? Maybe we fix this issue in the same way.

**Comment by OSFOSF** [comment]
now if user not logged in they are directed to the login page when then click menu profile and community

**Comment by OSFOSF** [comment]
fixed

**Comment by coiby** [comment]
I don't think this has been fixed. Users are still redirected to the home page when visiting /user page. Meanwhile, I've asked for UM team support on this issue.

**Comment by coiby** [comment]
I've applied the following solution as suggested by the UM support team,
![Screenshot_2024-06-24_20-44-06](https://github.com/OpenSanghaFoundation/OSF/assets/1511656/4fb0e734-5d8c-4a97-964b-5b49f072d5ef)

Now if an anonymous user will be redirected to the login page if he/she visits https://opensanghafoundation.org/newsite/messageum/ or https://opensanghafoundation.org/newsite/user

**Comment by coiby** [comment]
Oh, there is a side-effect of this change which is the user/USERNAME page is now limited to logged-in user only which is bad for SEO. So I reverted the change and asked UM's support team again if there a solution without this side-effect.

**Comment by OSFOSF** [comment]
https://opensanghafoundation.org/newsite/messageum/  takes them to the login page and thats good
https://opensanghafoundation.org/newsite/user/sam/ takes them to sam's page and is correct
https://opensanghafoundation.org/newsite/user takes the anonymous user to /newsite/ and thats goo enough
and google has found all our users so i see no issue here
