### ISSUE TITLE
Pop-Up Window Buttons cannot be opened properly with Middle Click

### ISSUE THREAD

**Issue by nowmichaelclark** [OpenSanghaFoundation/OSF#44]
**Describe the bug**
When attempting to open a Window with the Middle Mouse button, it does not open in a new tab if it is coded as Pop-Up Window. Instead, the new tab redirects to the same page that user is on in the starting tab. 

**To Reproduce**
1. Go to [https://opensanghafoundation.org/newsite/resources/](https://opensanghafoundation.org/newsite/resources/)
2. Use the Middle Mouse button to Click on the 'Audio' or 'Transcripts' button.
3. Look at the new tab that is open.
4. See that it just opens the same resources tab.

**Expected behavior**
When using middle mouse button to open these windows in a new tab, they direct to their respective pages. Middle clicking the 'Audio' button leads to a new tab that shows the Audio page and Middle clicking the 'Transcripts' button leads to a new tab that shows the 'Transcripts' page.

**Video**
https://github.com/OpenSanghaFoundation/OSF/assets/162073748/1db6468d-0ba4-464c-b2ac-ccc01af0aeb5

**This issue only applies to PC browsers and not to mobile.**

**Comment by OSFOSF** [comment]
fixed resuorce menu to open full page not as a up for both
