### ISSUE TITLE
No need to redirect users to /newsite when visiting https://opensanghafoundation.org

### ISSUE THREAD

**Issue by coiby** [OpenSanghaFoundation/OSF#47]
**Describe the bug**

Users are redirected to /newsite when visiting https://opensanghafoundation.org. https://opensanghafoundation.org/newsite hasn't been officially launched so it feels strange for this redirection. It makes more sense to remove this direction. 

**To Reproduce**
1. Go to https://opensanghafoundation.org

**Expected behavior**

Don't redirect users to https://opensanghafoundation.org/newsite

**Comment by OSFOSF** [comment]
no this is how botssoft set it up
