### ISSUE TITLE
What's "that system" which has market paradigm and the various hidden barriers built into?

### ISSUE THREAD

**Issue by coiby** [OpenSanghaFoundation/OSF#48]
**Describe the bug**

Quoting the homepage,
> At Open Sangha Foundationwe are creating, nurturing and supporting a community of practitioners of Buddhadharma, students and teachers, who are committed to ensuring these teachings flourish in the 21st Century without succumbing to the market paradigm and the various hidden barriers built into that system.

I'm confused on what "that system" is because it has never been mentioned early.

**To Reproduce**
1. Go to https://opensanghafoundation.org/newsite/

**Comment by OSFOSF** [comment]
THAT SYSTEM IS THE ABOVE MENTIONED 
market paradigm

**Comment by OSFOSF** [comment]
see no need to change this
