### ISSUE TITLE
An admin can't update another user's profile when his/her own profile photo is missing  

### ISSUE THREAD

**Issue by coiby** [OpenSanghaFoundation/OSF#50]
**Describe the bug**

As reported by Timo, when an admin doesn't have a profile photo, he/she can't update another user's profile. The error msg is "Profile Photo is required" which exists even the to-be-edited user already has a profile photo

**To Reproduce**
1. An admin removes his/her profile photo first
2. Edit another user's profile

**Expected behavior**

The user profile can be updated.

**Screenshots**

![Screenshot 2024-06-30 101023](https://github.com/OpenSanghaFoundation/OSF/assets/1511656/ec4310a4-7916-47c3-bec4-a8b6677208fd)

**Additional context**
A fresh install of WP + UM can't reproduce this issue.

**Comment by OSFOSF** [comment]
good ADD A PHOTO
