### ISSUE TITLE
User input to certain fields not sanitized, output not escaped

### ISSUE THREAD

**Issue by ttn-ttn** [OpenSanghaFoundation/OSF#59]
**Describe the bug**
Some fields in the user profile editor (and potentially in more places) aren't sanitizing user input and aren't escaping their output.

**To Reproduce**
1. Go to your user profile.
2. Change your bio to `<s>`, or add that tag at some point in the bio.
4. Save the changes and load the user profile.
5. Now some text in different parts of the page will appear striked through, as the browser adds the missing `</s>` tag before closing the body.

**Expected behavior**
User input should be sanitized to avoid dangerous input such as JavaScript, raw (unescaped) HTML tags and raw SQL statements. Output should be escaped (that is, for example, instead of outputting a raw `<` character, outputting the `&lt;` sequence).

**Additional context**
This is not immediately dangerous because Wordfence prevents the more naive attempts of malicious use, but it is possible to work around Wordfence and inject malicious data. This could be used, for example, to deploy malware or ads to other users (through XSS).

The Wordpress docs explain how to sanitize user input and escape output.
- Sanitizing: in this case, it's necessary to use `sanitize_text_field`, see https://developer.wordpress.org/apis/security/sanitizing/
- Escaping: in this case, at least `esc_html` should be used, see https://developer.wordpress.org/apis/security/escaping/

In general, as the [Wordpress docs](https://developer.wordpress.org/apis/security/) say,

> Don’t trust any data. Don’t trust user input, third-party APIs, or data in your database without verification. [...] Always make sure to validate and sanitize user input fore using it, and to escape on output.

**Comment by coiby** [comment]
I think I've reproduced this issue
[Screenshot_2024-08-06_20-30-58](https://github.com/user-attachments/assets/7caa3075-fdf5-4601-8b8d-170f41245494)

**Comment by coiby** [comment]
Upstream bug: https://github.com/ultimatemember/ultimatemember/issues/1546

**Comment by coiby** [comment]
[2.8.9](https://github.com/ultimatemember/ultimatemember/pull/1563) has fixed this issue.
